apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: kdb-{{ .Release.Name }}-pg
spec:
  version: 10.2-v1
  storageType: Durable
  storage:
    storageClassName: default
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Mi
  terminationPolicy: WipeOut