apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: {{ .Release.Name }}-interoperator-manager-role
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - instance.servicefabrik.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - osb.servicefabrik.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - resource.servicefabrik.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - kubedb.com
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - bind.servicefabrik.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - '*'
- apiGroups:
  - kubernetes.sapcloud.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - sap.com
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - deployment.servicefabrik.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - lock.servicefabrik.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - '*'
