apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: sfservices.osb.servicefabrik.io
spec:
  group: osb.servicefabrik.io
  names:
    kind: SFService
    plural: sfservices
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            bindable:
              type: boolean
            bindingRetrievable:
              type: boolean
            context:
              type: object
            dashboardClient:
              properties:
                id:
                  type: string
                redirectUri:
                  type: string
                secret:
                  type: string
              type: object
            description:
              type: string
            id:
              type: string
            instanceRetrievable:
              type: boolean
            metadata:
              type: object
            name:
              type: string
            planUpdatable:
              type: boolean
            requires:
              items:
                type: string
              type: array
            tags:
              items:
                type: string
              type: array
          required:
          - name
          - id
          - description
          - bindable
          type: object
        status:
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
