{{ $namespace := .namespace }}
postgresql:
  apiVersion: "kubedb.com/v1alpha1"
  kind: Postgres
  name: kdb-{{ .Release.Name }}-pg
  namespace: {{ $namespace }}
secret:
  apiVersion: v1
  kind: Secret
  name: kdb-{{ .Release.Name }}-pg-auth
  namespace: {{ $namespace }}
service:
  apiVersion: v1
  kind: Service
  name: kdb-{{ .Release.Name }}-pg
  namespace: {{ $namespace }}