{{ $stateString := "succeeded" }}
{{- if eq .Values.postgresql.status.phase "Failed" }}
  {{- $stateString = "failed" }}
{{- else }}
  {{- if eq .Values.postgresql.status.phase "Running"}}
    {{- $stateString = "succeeded" }}
  {{- else }}
    {{- $stateString = "in progress" }}
  {{- end }}
{{- end }}
status:
  state: {{ $stateString | quote }}  
  description: {{ .Values.postgresql.status.reason | quote }}
binding:
  error: ""
  response: {{ (printf "{\"credentials\":{\"host\": \"%s\", \"username\": \"postgres\", \"password\": \"%s\"}}" .Values.service.spec.clusterIP  (.Values.secret.data.POSTGRES_PASSWORD | b64dec ) ) | b64enc }} 