apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: sfevents.instance.servicefabrik.io
spec:
  group: instance.servicefabrik.io
  names:
    kind: Sfevent
    plural: sfevents
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            options:
              type: object
          type: object
        status:
          properties:
            error:
              type: string
            response:
              type: string
            state:
              type: string
          type: object
      type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null

