{{- $name := "" }}
{{- with .instance.metadata.name }} {{ $name = . }} {{ end }}
apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: kdb-{{ $name }}-pg
spec:
  version: 10.2-v1
  storageType: Durable
  storage:
    storageClassName: default
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Mi
  terminationPolicy: WipeOut