{{- $name := "" }}
{{- with .instance.metadata.name }} {{ $name = . }} {{ end }}
{{- $namespace := "" }}
{{- with .instance.metadata.namespace }} {{ $namespace = . }} {{ end }}
postgresql:
  apiVersion: "kubedb.com/v1alpha1"
  kind: Postgres
  name: kdb-{{ $name }}-pg
  namespace: {{ $namespace }}
secret:
  apiVersion: v1
  kind: Secret
  name: kdb-{{ $name }}-pg-auth
  namespace: {{ $namespace }}
service:
  apiVersion: v1
  kind: Service
  name: kdb-{{ $name }}-pg
  namespace: {{ $namespace }}