{{- $name := "" }}
{{- $binding := "" }}
{{- with .instance.metadata.name }} {{ $name = . }} {{ end }}
{{- with .binding.metadata.name }} {{ $binding = . }} {{ end }}
{{- $namespace := "default" }}
docker:
  apiVersion: "deployment.servicefabrik.io/v1alpha1"
  kind: Docker
  name: {{ $name }}
  namespace: {{ $namespace }}
dockerbind:
  apiVersion: "bind.servicefabrik.io/v1alpha1"
  kind: DockerBind
  name: {{ $binding }}
  namespace: {{ $namespace }}