apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Release.Name }}-broker
  name: {{ .Release.Name }}-broker-service
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.broker.service.type }}
  ports:
  - name: http
    port: 80
    targetPort: broker-internal
  - name: https
    port: 443
    targetPort: broker-internal
  selector:
    app: {{ .Release.Name }}-broker
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    service: {{ .Release.Name }}-broker
    {{- if .Values.cluster.ssl }}
    garden.sapcloud.io/purpose: managed-cert
    {{- end }}
  name: {{ .Release.Name }}-broker-service-ingress
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  - host: {{ .Values.cluster.host }}
    http:
      paths:
      - backend:
          serviceName: {{ .Release.Name }}-broker-service
          servicePort: 80
  {{- if .Values.cluster.ssl }} 
  tls:
  - hosts:
    - {{ .Values.cluster.host }}
    secretName: {{ .Values.cluster.sslsecret }}
  {{- end }} 

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-broker
  labels:
    app: {{ .Release.Name }}-broker
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-broker
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-broker
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.broker.image.repository }}:{{ .Values.broker.image.tag }}"
        imagePullPolicy: {{ .Values.broker.image.pullPolicy }}
        ports:
        - name: broker-internal
          containerPort: {{ .Values.broker.port }}
          protocol: TCP
        env:
        - name: NODE_ENV
          value: {{ .Values.broker.node_env }}
        - name: BROKER_USERNAME
          value: {{ .Values.broker.username }}
        - name: BROKER_PASSWORD
          value: {{ .Values.broker.password }}
        - name: SETTINGS_PATH
          value: {{ .Values.broker.settings_mount_path }}/{{ .Values.broker.settings_filename }}
        volumeMounts:
        - name: settings
          mountPath: {{.Values.broker.settings_mount_path }}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 9293
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 9293
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
      volumes:
        - name: settings
          configMap:
            name: sf-settings-config
      restartPolicy: Always
