apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-scheduler-controller-manager
  labels:
    app: {{ .Release.Name }}-scheduler-controller-manager
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-controller-manager
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-controller-manager
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:9877/
        - --logtostderr=true
        - --v=10
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.4.0
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
      - name: scheduler
        image: "{{ .Values.interoperator.image.repository }}:{{ .Values.interoperator.image.tag }}"
        imagePullPolicy: {{ .Values.interoperator.image.pullPolicy }}
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        command:
        - /scheduler
        resources:
          limits:
            cpu: {{ .Values.interoperator.resources.limits.cpu }}
            memory: {{ .Values.interoperator.resources.limits.memory }}
          requests:
            cpu: {{ .Values.interoperator.resources.requests.cpu }}
            memory: {{ .Values.interoperator.resources.requests.memory }}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /metrics
            port: 9877
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /metrics
            port: 9877
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "8443"
    prometheus.io/scheme: https
    prometheus.io/scrape: "true"
  labels:
    control-plane: {{ .Release.Name }}-scheduler-controller-manager
  name: {{ .Release.Name }}-scheduler-metrics-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    control-plane: {{ .Release.Name }}-scheduler-controller-manager